ContactField.create(name: "Phone", value_type: "string")
ContactField.create(name: "Fax", value_type: "string")
ContactField.create(name: "Email", value_type: "email")
ContactField.create(name: "Web", value_type: "string")
ContactField.create(name: "IM", value_type: "string")
ContactField.create(name: "Address", value_type: "string")
ContactField.create(name: "Zip Code", value_type: "string")

ContactType.create(name: "Home")
ContactType.create(name: "Office")
